[build]
  command = 'npm run ci:build'
  publish = 'out'

[template]
  incoming-hooks = ["Uniform"]

[template.environment]
  CONTENTFUL_SPACE_ID = 'Contentful Space ID'
  CONTENTFUL_ENVIRONMENT = 'Contentful Environment'
  CONTENTFUL_CDA_ACCESS_TOKEN = 'Contentful Delivery API Key'
  CONTENTFUL_CPA_ACCESS_TOKEN = 'Contentful Preview API Key'
  UNIFORM_API_KEY='Uniform Optimize API Key'
  UNIFORM_PROJECT_ID='Uniform Optimize Project ID'
  GA_UA_ID='Google Analytics ID (optional)'


[build.environment]
  UNIFORM_CLI_BASE_URL='https://canary.uniform.app'
